env:
  node: true
  es2021: true
  browser: true
plugins:
  - "@typescript-eslint"
extends:
  - eslint:recommended
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  indent:
    - error
    - tab
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-var:
    - error
  no-console:
    - error
    - allow:
      - error
  eqeqeq:
    - error
  curly:
    - error
    - all
